name: explorers_map
description: Кроссплатформенное мобильное приложение для отслеживания путешествий с фоновым геотрекингом
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Локальная БД
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Геолокация и фоновые задачи
  geolocator: ^10.1.0
  workmanager: ^0.5.2
  location: ^6.0.0
  
  # Карты
  flutter_map: ^6.1.0
  latlong2: ^0.8.1
  
  # Сетевое взаимодействие
  http: ^1.1.0
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  
  # Push-уведомления
  firebase_messaging: ^14.7.9
  firebase_core: ^2.24.2
  flutter_local_notifications: ^16.3.0
  
  # Утилиты
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  device_info_plus: ^9.1.1
  
  # Математика и кластеризация
  collection: ^1.18.0
  
  # Сериализация
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
